version: "3.0"

services:

  zoo1:
    image: wurstmeister/zookeeper:latest
    container_name: zoo1
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      #ZOO_SERVERS: server.1=zoo1:2888:3888
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
      ZOOKEEPER_SERVERS: "zoo1:22888:23888"
    logging:
      driver: none
    networks:
      - hack


  kafka1:
    image: wurstmeister/kafka:latest
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "PLAINTEXT://kafka1:9092"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_MESSAGE_MAX_BYTES: 150000000
      KAFKA_FETCH_MESSAGE_MAX_BYTES: 15000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 15000000
      KAFKA_MAX_MESSAGE_BYTES: 15000000
      KAFKA_NUM_PARTITIONS: 10
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
    #logging:
    #  driver: none
    depends_on:
      - zoo1
    networks:
      - hack

  kafka-kaftdrop:
    image: obsidiandynamics/kafdrop:latest
    hostname: kafka-kafdrop
    container_name: kafka-kaftdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka1:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    logging:
      driver: none
    depends_on:
      - kafka1
    networks:
      - hack

networks:
  hack:
    external: true
